# Generated by Django 5.0.7 on 2024-08-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstart', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
