# Generated by Django 5.0.7 on 2024-08-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstart', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=150)),
                ('technologies', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
